export const siteConfig = {
  name: "Jiazhen Xie",
  title:
    "Jiazhen Xie - Engineering Leader UK | Oxford Alumni | Chinese Tech Leader",
  description:
    "Engineering leader in the UK with 14+ years experience. Oxford MSc graduate. Chinese engineering leader specializing in tech management, team building, and software architecture.",
  keywords: [
    "engineering leadership",
    "engineering leader UK",
    "Oxford alumni",
    "Chinese engineering leader",
    "tech management UK",
    "software engineering management",
    "engineering leadership blog",
    "Chinese tech leader UK",
    "Oxford University graduate",
    "engineering manager",
    "software architecture",
    "team leadership",
    "technical leadership",
    "full-stack development",
    "distributed systems",
    "engineering culture",
    "inclusive leadership",
    "cross-cultural leadership",
    "tech leadership insights",
    "software engineering best practices",
  ],
  url: "https://jiazhenxie.com",
  ogImage: "https://jiazhenxie.com/images/jiazhen-xie-og.jpg",
  author: {
    name: "Jiazhen Xie",
    nationality: "Chinese",
    education: "MSc Software Engineering, University of Oxford",
    location: "United Kingdom",
    expertise: [
      "Engineering Leadership",
      "Software Architecture",
      "Team Management",
      "Full-Stack Development",
    ],
    experience: "14+ years in software engineering and leadership",
    languages: ["English", "Chinese (Mandarin)"],
    twitter: "",
    github: "https://github.com/jiazhen",
    linkedin: "https://www.linkedin.com/in/jiazhen-xie/",
    email: "jiazhenxie515@gmail.com",
  },
  links: {
    github: "https://github.com/jiazhen",
    linkedin: "https://www.linkedin.com/in/jiazhen-xie/",
    email: "jiazhenxie515@gmail.com",
  },
} as const;
